#ENC[AES256_GCM,data:aHvRmLHwMeyT8NoD73csJe2AeIAXSP6gQaUPNZtqw9VeiXVXFIMAetAWxo534GXFg6fc/JxcpNJ2bwSlLZNjFaVQOHJsp233tStV,iv:5DVBp9o2PQEiUwYt9p5vuo5wjVrvKG5I1zgm52JGm14=,tag:28Aast2TlTaWS3peXnLVqw==,type:comment]
#ENC[AES256_GCM,data:OGyevLLC0/ZB14k0wlC1SDfcgcGtOge0+FKJDTF8G9UAg4R7Cx44/eC8hTaX1isBPgHCU5W2UH9ZNhiEGDCurylYXpHZWC4DlQ==,iv:xbfXTEP9nXYpo4xhsKoqfcIr072f9mzLLol+FAxBNTQ=,tag:Ur+WRgFCLELiY82xMMhgqA==,type:comment]
#
#ENC[AES256_GCM,data:3GuW3jysG1aLIua8ZIVRXbDzPGklsysT6/srk/+USh/MoK7ujqJ1itsZW4shfGVGnlIUW56xfniRKz9wi6mDV/opXAfZiOxdf7cNtBw=,iv:sw12KgltHj/ijFgedA7AqZMaWI/KRoU7AtpHhyp3SJQ=,tag:cTHXEE+Sfp0n20VIWBrYlg==,type:comment]
#ENC[AES256_GCM,data:7yvV1/FX/O7I+OiMVXDC8X2+FnutumrDRnDxF0Px+/IE6h7vVVviwtW7vXmRuUYLdqQXP9bw2Q==,iv:ydofIuEeQdHufods9lsDAPedRW+AMBKpJih2keuYEWg=,tag:8kVs8qfIzUM+qI3QvAUpCA==,type:comment]
#
#ENC[AES256_GCM,data:jfy52f+TW7qjKacEydxs2B69EqJjuc7syC+H5vpPzwrNcLmhmL17fWWsbM2X9vVxlpHjsA==,iv:MnLCWJRoedQjCtfyGSf4bpCbQ7K2fLcc2jX+CY8dCyE=,tag:MZeYKkP/5CkUWwFggrn+1Q==,type:comment]
#ENC[AES256_GCM,data:59AV0/zypvgNhuh38YKVyl8eFFNL8BbWLB9tUkj5AaYSjN6V2ShVZbptxzHkJi910nESFSeBe458sERreLDBlrU1gHLDS+iM,iv:cGR5tYPkTuprkpFNuLQ6EYuYnfhP++IzVHM8io8+5u4=,tag:vpTGqZKFueFM9LoIxErYCg==,type:comment]
apiVersion: ENC[AES256_GCM,data:wos=,iv:jkksykzbOiApWeTE8/+szEZqrC6+x6882K8cf8SEwYA=,tag:5j/DMHHC7fCxwqlAuus37A==,type:str]
kind: ENC[AES256_GCM,data:M7+xSodt,iv:IEr1NWpRmmea77rxJQZm417Qpzxy8GbJzQIVpmF/Nbw=,tag:1U+wjeJq+fYujlbwJTZ77Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tEDW3hj803cN2OU=,iv:/9cs409L/1yW5W7aNaN9MeVq71bjkiwM5KM4EVRlDQU=,tag:Cj3JwHlrWlD4YXCSIufDUw==,type:str]
    namespace: ENC[AES256_GCM,data:JesXd0Zp,iv:FO9xGQN/gmwobwLMvlIcCJ69nO0ue8dNZRmV7/y0qPg=,tag:ZrutwaN1OBSIdBCem1PFEg==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:dzjDuysv,iv:Cwr2sx+RnNb4qLDYxi69tocGQ0k7bpjcY5RXCkLuq6Y=,tag:ucyBPmwbG7scIT2Y5TRkUg==,type:str]
type: ENC[AES256_GCM,data:rbmflr8Q,iv:HHHxprrCT5KAbiSVXlBWf2wz6UV/rqmGe6emWRcw6wg=,tag:NqumMW7R+Cghq66azpvIJQ==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:rz6RyXf6ZIw4Qb1sb9AAwUtv/ppmMlEtErzQytsPQC0laYnFsg6ycSTbO2DOARU/ot4YXM3C+ety3q3Xr8/0gw==,iv:pdydfcDvFMKIXuygar9KZCKXKgbjZb2Y6STM92z2lW0=,tag:7CoM+0FGo+ez/StHZCAZNg==,type:str]
sops:
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycDNzMFpXZ3RDSG93ZUZv
            dWp2Y0JKWWovYkRaR25RMk1TeEQ5QW5uVVJRCmVsbjVyOURPMUxGTTV4dmFicnZ6
            SUhzTjJoR2dFVng4NXhUWWRRbmVjK28KLS0tIGJhUDlkaVJmMDBpTUJyaHkvWXNo
            cXhiWWZpcURNQlhhN2JWbnF6R2w0SW8K44whJ7/9K/AXMtG66s4GJcb5FL5DwDE9
            S0CuRfLVJjC0cEN8mVQcXrH6wF4Yui5Nuy5BBPFb4y5B0aiHPC7W7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T11:45:19Z"
    mac: ENC[AES256_GCM,data:feb6V3bhn642Nw4p3YVjApZVKPXUNBG/+Qp0TvRKJSd/fyqz965XL55wy0lvfervncjLwM2CcOIpLS1sGWep1otVjmuQELksaVhs+F+MyEqbjSsJzPUvfxTQAb9suXpduLLPu6A8zixgMqSwXcwv9e/E8wQKQEWtYFv3MTPDsSA=,iv:5VtmCLn6OOG4sydoai3tD2TlvDhKfNuX99xtAvQvNx8=,tag:abTJqj5Z7nSvXgTrgl98Sw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
