#ENC[AES256_GCM,data:fxBLsvjTzAK4BDDuO/lMMFWQbOzNB6e2XZSqhmAzaX1pHHTdOUFUGy0mO8mjgBQd7Ziu7rpCV6yDl9XvZAz43PpXB6/gr1nIDctYaZ6vMw==,iv:WLMNQodCTbo3U5tPsa9QdDg6OS+y2klhMq2xk04b7bw=,tag:gOR0vBubLTlNhcjZ2nKb6Q==,type:comment]
#ENC[AES256_GCM,data:AnlAlYwOafxhZdZ0GZN/1Zp+BjU+yZGnYq0FEc7rnbl+k9orTpTjb0GgY7vwrEr2v0qMIqQd/6ToyO3CGXDeLYTaozvGyPs=,iv:1vCv3Gi88gp9IyjJKn9jk9LgvLHRlpb+SrYrsdCw/dw=,tag:MooZ7McK6APFps8TfQXd+A==,type:comment]
#ENC[AES256_GCM,data:EwClOUNB3xxUVgOrX9V8lqV0oTg9tUMT8CBdHllTA5jaghg5lwF4ME2IFoIK8fGnSeL60yxIy1doBtXu/n1YR4XiH41kgDRx,iv:GAfR+oc6i9lqCCFX+x5BOSuqrnCyKcl25Kze7VJkfe8=,tag:20g5MWcn39M62FzLbi8n7g==,type:comment]
#ENC[AES256_GCM,data:G4Ro83NwJZ3YXzzRpFHcv69VITxapyB9gbYV/ki1/tkdXEQ/miYSqNJX4GV5pClecUuoyMujxfheRcR4xL1stg==,iv:cDOrsBVRsFzqCKfObIzeboNtzrfUmUyaIIgOxr1W644=,tag:ogNYLbGSGFYhj/zKazACtQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:yLM=,iv:SYaflhzmX1YdJ3EmJ5ju0scXW1JJQGB+V5CMgtWQZOs=,tag:x9cmKQB27PPNHktbvknVVA==,type:str]
kind: ENC[AES256_GCM,data:rNtZdyLB,iv:0oYj6E9rAABN7H02njVGCpvyw+f90iSvPrtHQerFTlU=,tag:zjS45sRWWMuOlDX1cdc2cw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4KQuHwYjUAR6wAa2xMWJ0A==,iv:Pxlzp0CC60e6RwrHMnAn1++Xntk6uY4Vr8kKnNFMvlY=,tag:TUyXMGSwXawu4mzD7pLEug==,type:str]
    namespace: ENC[AES256_GCM,data:Q24OHg==,iv:2x+EOJlMX4O0DTldn5Bp4llps0D3BgQ/3wvRviWKVbM=,tag:smqnOIFOHk4H4tLk3FOnVg==,type:str]
type: ENC[AES256_GCM,data:llSIicSo,iv:bJtwHo7kxwwHRSodIUB/os5WYxE5zediTBoPu97qZl8=,tag:kacQ9sUEKpT6tp0eKYxkcw==,type:str]
stringData:
    DEX_OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:kW6NFUrU/aaYmUKyODGkM97e1ZC653oBjyPLQszZmi7hWpgFHGdY2ZnlaItDsfxiEiykdpsq6e3jFhyatqFd3Q==,iv:s15GvEQGfNgf1aSTJhR8WSGtCxBPGSvBS4xh8wWf2GE=,tag:a9X8+fAgMSNMTk0Z/tx3MA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:IxRgJi+nxuFweEmuFjr9E0bIkqEgJPELXclTv3gT/kA=,iv:lpD+Lv1E1cHWSiX7ydnQ+iR+Cynx9P1h9lH+EFYzYLY=,tag:gruDDqswH7WEOMoOzk/3wA==,type:str]
    SESSION_SECRET_KEY: ENC[AES256_GCM,data:BommFZKlRnoK26kDcNEs+fWl8GUl4bH3lBYqxscesd0c/n7HxwznjxP4eQfR/ij0sIxeew4n6CLIymx0Nlm2c6AxzDCtaVO6Uktri9xyUH74kZslVMioqUE7vcBX09oTh+EWd4W5uk0Qm13DPfDpouASokHPOFqWKuNRqfZA2Z0=,iv:ZCsnD3zC9uFzsbB5VMC1IC82E29COV75NmruGfAUCNI=,tag:2qRquHJWQ1XiU3JY76zaKw==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:gOmPN8ioT2Z34r8Dv/sP32q5tew=,iv:DQ8KTWN/FyLNhQG1nbJQhdNsS8K5Z4rmMK6xp4qzKsc=,tag:WJcrOu2VWmjeiZ2zbljFvw==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:Edmg5FJ3qqmlOWMdgdY8E4fEDk287dZZTvjs0AZFRCDZn6N8suynAg==,iv:qF2rBnOQGUas+u4k9P+Jb+/jL+5KkkkOsgXoVakIZds=,tag:+VgIGdpyL8F/4L0IlNjULQ==,type:str]
    GITLAB_CLIENT_ID: ENC[AES256_GCM,data:QBKX5JGXqJsji3Ko1RFk5ZHtUgRiwXoD7lAXA3r98RcnGveDOMnQTD6xpL2lNgdjlhgqjFQ0PhmmA5I1dXn3Aw==,iv:3309sjCwGtYnHcpvC9GzXrVrDRY0UvXSoFpp+e/BqKA=,tag:HYJcXDE/cXpam2Yf4q+h1A==,type:str]
    GITLAB_CLIENT_SECRET: ENC[AES256_GCM,data:6haji0KpnKluX1BnJw1z3eZNnjbJZOfsaikBU5oBAYDEUTSeJ/HPGCKD6j+TuCwxAQjtqe0SRt2RNP3WmL4m1x7N400ayQ==,iv:wVrmLoLH8GFaxVv2ZJSRtu5dArbUHRv4iOvTpicZ+dE=,tag:gF/I95FqH15hu/lW7HGysQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:Ctpf404e2nuU8QXIkLByaKNtGWXxBD0oSuacfzRvhIQ6/aLgFhybhFNqcT64Wi+qeEpe4YTTlZ0IUh7NR15EVpWgQPynE3WD,iv:Z1A021WbZDrOzhM2g+LwuEai+Aw+fEf9682gFhrQFeY=,tag:OeMP27rzW6oabufjd6Nk7g==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:nFvHZ8JNRlfU8XdcZSX+SFjl+o5nr+szR6pplk6ouwoGiiE=,iv:2zy4vqkagHBcEvUDjaJ/aKUKVrDkgxvq06X4ubigHoA=,tag:jWRQmDg9L27TYiddfJvOJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdUVjUDVvNWdQV0MwZFhp
            NWZGakx6cHhTcGZlMmo0M0ZlMFFWa2JlSWdVCjVJdVR2a2xSMVlhN1d3bmkrMVJX
            NFBHYnpFUU4zZjI4RXM2eHN1eWlzdG8KLS0tIDEvSWlzNWF6U3JUQXZSSmhHQjUz
            ejVlb1RSTmg5K3pZbVZLc3FwUFFLYTgKbNxmIyN0yCzFNjHk6RqY5DJHJmzKQRyW
            /5/n1O/1TodEPI49VfCIg/uiT4rYCTbVlkVt7SRjOVQihlrA67jpKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T00:21:06Z"
    mac: ENC[AES256_GCM,data:wgNTkXO0jm6pwpgLv5IcAnDAzXAZFp0+W9fIPM24lM9XtQ45xrBWb6H+g/IRkl65kz1hS++8m02CW0G2qIK0EBTwVCBTK1R+h5kRfTwpumhpESMlCbIcoS7FfN5agwH9S7vy/O9iq9wFNTk4eDZtzaiKu9MF/FmAURLE792X/oo=,iv:pU0vf843/Xip9HovcBDQAJsof87OL9hPRXZfPvdw6hY=,tag:agiO9xLIwff/ZZYHokmJYQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
