#ENC[AES256_GCM,data:VqdyCL40VS6Shd5PY+BaCDtCepJAZfuYEMAATUoHzDzHld84Blu4KVRMgdZp0WwZr13h7Tl57v/IeaIjKQ==,iv:CcASoMDVSAivvlokienSBxYuMbmmaQaZ2Os8abwfx7Q=,tag:gNaAgqbo8zQBhWbXerp+5Q==,type:comment]
#ENC[AES256_GCM,data:jd+ij7CmqW8/N341pKxgf5KQJqTitkOQZmS+Hj/8l80HcIfORAPvBzi4CJoDChGmo9Clu+gqOtEpVjAuNBTFdnsE3tm/M4NnhXzyDkg=,iv:WY3gqx1D/LLMO5MapVmjdhg9DPQJAINI+uP1Vk0+dPc=,tag:b8ngwe2RiFs8ou3qCaRndQ==,type:comment]
#ENC[AES256_GCM,data:2Dybznv47nOuHI6On3OXQQCHI7eio02HXoD4G8hwUHKcE5CP3fIwosqas0QyRf2dxLe3/PIxhkh9Rc3H0J7VxGdzHRPkgzFs/t2XA1je,iv:xUuj4hx8QAbe6Yes9ASFWGfHJSFUQd50Hd112EO8nSE=,tag:m7ow5uquPzwSbIxxJQ7u/A==,type:comment]
apiVersion: ENC[AES256_GCM,data:3fw=,iv:SV+u3mwfvSAnJupirwLQ6i2NEOSntH4dnVxP2FQphVw=,tag:yL73QEnrYDk3cRBAir5Xpg==,type:str]
kind: ENC[AES256_GCM,data:sSWHX/xu,iv:kJrqAVVa74QqLQmlgNlw1aeUcCagWyrfWiS7WOZmXnw=,tag:IFV8vzChRA6ubXtR2RPi1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KN9+Qa/A2KoAc3/HaKgR,iv:RmghRVOqTGG+eEBgM6Eefgob8VpCpf3eeoUeB7togo0=,tag:CRvvMddHlfp2jdc3h7g17g==,type:str]
    namespace: ENC[AES256_GCM,data:x/vcnA==,iv:x2vZV4PaUU0IKKxxqjmjd/DTVclFMtLK3d43RlkY0eY=,tag:56MhTdjh1S3sVWsfaQrKOg==,type:str]
type: ENC[AES256_GCM,data:biWYyDR1Ng5i5EELy6fhfEScMjmcxL7H,iv:AvfOAJ0SAtiaYSNM8yMJfSYf8JhJoFCaUQ/l5R3Vteo=,tag:K921fW9yS7tLoRSbr7oyoQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Yu7xgD/5,iv:2FBtj1wx+Py1/Sv+pFwE0jLYyy2iIuuRh6k9Ia7rYPA=,tag:qd5rzFOCiO0bYzKDLOMQHQ==,type:str]
    password: ENC[AES256_GCM,data:sQFJVgDOZR9hZ2FpeZneS5rViEcWNvfPEk1CFKKJsLbNldbpmybHHtPWzQ39Ui9OgCQKtVpwZ0NRvAwwsW+77Q==,iv:3Y85uTHJMTt2D8b+487ADnN3VCEzyYlEGUPwWsgQgGs=,tag:MW45pbCX+UR2gn+VCefAvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUUFncXpxbExMNVd6azVh
            dEV1aTBIajkwUkNpekRQSE1GR3F6cEFoRlhRCjEyYk9nbjZyTUpWMCtJeE9lYW5z
            Z1hBTXVMSWJzSW1YR3V4bFQ1VGtaNWsKLS0tIG9kc2dwYlVsZnhiRE1VKzhhL3c2
            Ri9BcW1DTHltbnFYU2s3aVV4UGRyNW8KSp+sZ23hoFOKGvuFeCckl/JslxxXnbS/
            JkjPzwzwuS+TctVs4SMR7QnKiws6Kgzm1eNDbB5tzBXvSeXvsoUXhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T00:21:06Z"
    mac: ENC[AES256_GCM,data:ZZ/xH6pQJGIFUyW+O9IcfEFfxJ8bDhKUneBWy7gBr5D6IDitxL7JSXALpvoTj7jufcrlMIYXRQZ13KkAqPPiKC44zp/xCnQsVGu5wI0n+JP56DoPCdA4rAGfO0r1slzhhyTEhJFis+3ME5eGFsHBaiJnSRcxrT6msODjvNC5PTE=,iv:eHECUJ2+8qJq+i0WO6HKssN+VhQCzu18337QeZmng2U=,tag:VIUmBKH0HwZ+T6xzs4tGCg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
