#ENC[AES256_GCM,data:esSBgS9lgblWeBcUD0iY0VYbczvnic6eZN2Nne9uYdkPDgL7AtXoLIq9Crp+FicMCpVP8eFGTa+D5awv3YxCSixgIwQNZOuT06rEIQ==,iv:wHrFyjX1M5nHRcnzNMp48HWGDZb2BtalI/+q/X1p1Dw=,tag:/7n4uctTJdnxbxAjByhQzw==,type:comment]
#ENC[AES256_GCM,data:DW5fCR40VnWLPN2dqYFA3WGYZ0Ow3LbYOlj61WjgY1RCWN/LTp3u68q79WVQhZh0CLAAXCByjqoJkQTzDA3wVrqMjCI0o00=,iv:XWoSDHW3qy2A0A5dhX0bFaVlILKzUyFTSBvfKKqPSUU=,tag:ADa2KwCVp1Ymol+mUjNSaQ==,type:comment]
#ENC[AES256_GCM,data:I60cnA6RCUV5r69mjPDwtVRRD0kswuXfczkbCUHO1CVGhllh6XKZXycRxk/T6jGyDidUTiWSQYipSnkguCCZeJr1gwskCoQUNb7X,iv:7C+AD/kiEvZztG3YqJxzv5LOhto5wyIy4E4BUZLY2qo=,tag:hY8EQFmZvH1VieB1q99zzQ==,type:comment]
#ENC[AES256_GCM,data:d3eW276mi7LOqR9+RNTB6debAqyzo8yuL8P+sFV5CSGw/zaxSsTIQoU=,iv:OEJzN01WbU/xKnucPxcxfPYhwyXMCASKLAH9hwMI0QQ=,tag:T+L5t6by9RY3dgwVE3hZEA==,type:comment]
apiVersion: ENC[AES256_GCM,data:2l4=,iv:e6nNfk2x0imfkz483Wfj/cn2euvukFo9Mi2ELYZ/ZP4=,tag:RZxDN63xEifS+CI6XHFL/g==,type:str]
kind: ENC[AES256_GCM,data:uQufWGXf,iv:i8GTtYES73icA4+f2fsA8tTooRbKs91C81OD/Q/GrNM=,tag:NSA6gLafSeC+M3RNK8wPBw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QFdg7I0GqQgmj4TIqVm/TMkIzrcR,iv:3OR5urtOHq8ivBFrWJzfgORNtihfprWCMjl/ym7eV+c=,tag:z9GyxseSQdZ4KYZPCU1vOw==,type:str]
    namespace: ENC[AES256_GCM,data:3FLoqA==,iv:GMG5bdbndnw9h3C9AhHvDp8+xeLxuI6OLfgVUWsxxRA=,tag:/H8C6frp9lBksY3LwFDRoA==,type:str]
type: ENC[AES256_GCM,data:mmGV005m8FXzhaUiGwSv7jN4u2wdkHda,iv:HTPMG6kHhF23DluebJ0LGJ59oD6hPkehRYTG72ERWXw=,tag:3qDekcub8WQ41YBgGzPMNQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:TYfvxmalSZ8C5e5R,iv:2Uo3P7QtE0NeNWUD5y5zTDkMBDNBAb/wrSPXUgYkRQU=,tag:2x3Qk92Egr02o/RqqiXEOw==,type:str]
    password: ENC[AES256_GCM,data:LCiydiLiWw5OPA7YPoFr29s5O74O8XR2zwBXfhABgYwl+YVs397uGQ==,iv:bRPz8kfzkuAOnuRWwQE8MWf8MpbCpp26KOAwXPN8aaM=,tag:oZG++IuSYAvKN+7ky9vEqA==,type:str]
sops:
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSi9zU3JhbWVhVmQyVXpU
            Y21TS204eUs1VUtaRFljQTVjd1V6UHFrRmo0CmlnSmhSdHhLVTdTVG92QmIzbnli
            bWg0U2VKaXJ2aEt2a3FzMHNhQVVaa2sKLS0tIHBGaHVsZ0tUMXIrcDZjaUN4K1Q5
            dCt1RnBwMkZPQkZyVkhwcjAwc1pwQkUKih2V4TH72JHy9sO660bgvnpa2TwWQwts
            eJhsX3/SnhD0WcgDt8WdbP2dhyLZSt6XEdgSaYwFqURSFlH6ixGasg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T20:57:01Z"
    mac: ENC[AES256_GCM,data:4iQOhIJbVefOLRhY3idIGQQz27Uj+w00D8sQglETTSQlyd4jA2x9KG9AmgRiNc6U+zjufyf1/ak7xP2KhMVs0cbVI9UaOWCvSJaAgW9CGn0EscI2VOkhtNsXidB81N2wSyKWR7sSruXoSOa0CM0eJ9fDqSpcXh6dXRJ5MGyppk4=,iv:Nt4Lhxzl7DAa4WHM6FWQZz1u0u7oNbiCBQ1qBw5fyu8=,tag:/1jXKDsX4PbpzMYjxjr6cQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
