#ENC[AES256_GCM,data:VXOzjRhL0T8QUI7wo04LkeMcM+6qMnPxOcfUOclx+2E5HBBAU9MBVFYCzVWxv4bvNHn+Og6Qi2qDlTAFSqg/gtWZsp3jtA==,iv:hEKlFlvv3moeowBskxDf+FIfepXS83o6mLqY23yg30g=,tag:UX1M2yrOkWEarOQxj52Tzg==,type:comment]
#ENC[AES256_GCM,data:76hXVbz6lXnfmuSwhrQGPQRnYvDeSDrGk7VcKMUdqKldRXy/SpK+uW9DnLxVDvz9geomF5eb4lBYUQtqN7K4X3fx7gJsiDc=,iv:kNn7Jwrgk7b6OLNEe0nZ/00/+9hgWNbScLGy0US2yv4=,tag:WbRkhQ/p9kkk0BDevEgzOA==,type:comment]
apiVersion: ENC[AES256_GCM,data:71Y=,iv:B9da8fOG7avU/LDJPcRdKsIjt7yioTBqE4xqIP86aBM=,tag:DIsqeW692ZwGvB228vF8Hw==,type:str]
kind: ENC[AES256_GCM,data:siOYFLyk,iv:khuNtASotPwHL6S/6wimNaBvK2nsxm2vjI0PBpfgXyA=,tag:0lHb65q6+TTPdxU3KvD12A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WeLxPFcjX6nXlSOMySqGIu0l,iv:K3Zh4ChcyoZL5U6oGll0up7K5CdLSKc9Wbnuo76t/oo=,tag:3fVwNWC4sG4ynPHa01Fx6g==,type:str]
    namespace: ENC[AES256_GCM,data:w6kgoQ==,iv:hGlQXajNQatp+7eNY6EqBGaTr+sWjAQ4NpLzFCZikRE=,tag:lA873reOCYpy7BJYvJRqag==,type:str]
type: ENC[AES256_GCM,data:UtHJNr3urdOl43VcLer3uFyzzTuyafRq,iv:Qvl5y0OZmXqVRLYHU5v01z1nkx0b1T41JAIekJ5UwrI=,tag:ou00ByIak4aA0usL5fKY+A==,type:str]
stringData:
    username: ENC[AES256_GCM,data:r1kKMkFHfQQ=,iv:rLetU3ROOgH0XGBWej6YW/sNCpTuWzRrlYZzoooYmFc=,tag:x6+TetHI9TNwEoP81yd+6g==,type:str]
    password: ENC[AES256_GCM,data:jIQqdasH1CdcFaranOu1M5I6EIrOHlPHM6R9SfHPeqIN7fYBrEW99y1HnDejjapN7VCpPEOAQFHgUHWBguhWdg==,iv:MeKBw8pY9gg6sxjYyFnsqG7XtakYg3yvoxp0rFgm+yM=,tag:u04LAf4QgSVuE8ievsiPVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL0tQZWVkNkZrbVgwRUxu
            am1uRzUxR05TVS9ZVVE5OGtxUlplcUtkUlVZCkhicnM4R0NsbE1HV3NzMHB1S3F4
            MWsrdXVRNzRIRkJFWFcwNytsOHM1dmsKLS0tIElOUVE4cXc5NUNvZ2dlMGM4RzF3
            SXRoTWFwZmRKUDB4OHNEelYxODZmQmMK0Z3Hiqf08DzWSlTe1C3u2ruTwlh5SwNB
            SK4cYPWYlmz9ZH//u3X1Eacx8+/2kZcCCwNSF1YXZqyq5kFk5QSevg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T00:21:06Z"
    mac: ENC[AES256_GCM,data:kzLoca18kJGbtimDa7NsD2q2WTtIX6GL8b4Wakr8XPdkISnpUvUR69NX5PYHXpzlIuheiC0T4UGtbIWnc/jU02qRPSA1830AlVtXNKWMEKLlnER7FUyirhPjvkSMiATEMi+8e6qgTZN5ZVVSW96Vkuba82qEq7iBo+KI0LSp6WQ=,iv:UW74rrsSfBBBHFMs41fmUJQTKPeX3E0DQup0zFQIncU=,tag:WxAcUESav9kRgysKX3jHQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
