#ENC[AES256_GCM,data:CTgYaRyK5TiXf1/e/BvcJZ9zZPw6OBhRTZRJcgO7d480RfAmW0HjpqBaA7uM4zbAbRtYhQXUs0FqsROFxK1mbKZllvEX0JrKdsnD,iv:skUaJo+RM0EB7NxEH3rkt8U0swMFq2vGgAdZXwjlDDU=,tag:Ogr7PxjwFeZ6nOfh9tGA2Q==,type:comment]
#ENC[AES256_GCM,data:qKyfrh4w/tlkKSdp4OUKqgAtCLnfaREcF+LahxXVgr7NwFUn1eU2LI2vCxEyRNVcy9KO9j8/Lc/hk4DgtduL6ZyQGx+eLDiUeqyk2Q==,iv:rf/7g7XhE4MZY/B7dn7Kr13YmQcNbdzgBEnhP0zB1Xw=,tag:BzIuxFAp9eDK9pU0o/ldng==,type:comment]
#ENC[AES256_GCM,data:9H+KXWF/a1mKHmww+LtlV8KfBH0ZcTLftMQ=,iv:I+waAFkkVRwndFqJsy5LOTsR4kqZqkXK9tRARQAuz08=,tag:vxgOzTgnaAkSfzvs6ceNHw==,type:comment]
apiVersion: ENC[AES256_GCM,data:7bE=,iv:uROvzR34lDjbKFA6Iph0GLNOX5D7rdHcNMZ+uQknWK8=,tag:x1gttm0fzojTPNVTlofN0w==,type:str]
kind: ENC[AES256_GCM,data:oGCpbWUi,iv:YFTc2ZIv8ZQsgYJzkok0pxnQTGHKPPX2j8nQUkDPgs0=,tag:G2SuCGsYwjORV3S5DWZrDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HvLGWjDgXit2s+DV,iv:H8KfPNSGXDpoVKXr2sEddoBUzJJ/C6lrAnoNMAUxhKc=,tag:1l5FIwq8nHMiVEK3EbHzcg==,type:str]
    namespace: ENC[AES256_GCM,data:gOduzw==,iv:eToTlOdLIFdB4O2FYR4zqzfw8xAYzhOIDn27p4nGEl8=,tag:Cd7TFjQi1YWZ7B/X1eNOgw==,type:str]
type: ENC[AES256_GCM,data:r24esjKx2SzMM/DIldWltFtytytAar7Q,iv:AN/W5YRyo81wi1CNIeYH2KVmdVAkHy67QO64keQ01NQ=,tag:shYWJsbH8dB4KpAazNiI6g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:yXgc,iv:Q1jBUGV+lvCK0KZ+evx0WEXZUurlkxFk9Eq/Je+9upA=,tag:isgAdRpdbRTH1YtfcfEuhA==,type:str]
    password: ENC[AES256_GCM,data:aSGjaiCAIEXGTwb3qZFyo2uAVlrUNCtswgQ8e8rQkUexgylDf6DPa5lLIgthOPju6atHzi/SkvWoUSdnyrdHeg==,iv:bAyjCkdHiUIziwzKaiEryO9F1Ylcc5ZE9tsJVOPe+AE=,tag:89cZLNjz9Bn1HaQWuPhcCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVEx5SlRzSnlpUHlRS2Y5
            VVNZOE96VjBPVGVMNEI3RXIwQjRxVGoxc1hJCkNPMVlqOGwrdTU1Rm5CU3NHVGdS
            K3hObkVmeEJNV3l1UWtqN1AxR3RWUG8KLS0tIEZ3NkU2amM0SGR6M1dWSHM0WElk
            YXZsYW1Od1B2WmYwS1NIVHlybUxJUTgKlGfkkYgZvhwksJJbwiHJ0CJZPC52mm1Y
            +LCJLOL3y8pTiKfHJPBus10lPv4A8n4jXuwh20LPciLCQVoIXMEKTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-23T00:21:06Z"
    mac: ENC[AES256_GCM,data:nvqjqh0KdwDMucn5C4bmtAoTrETMOkHg+oeX0d/dqRPdgZcnYIp5EwJqkMozizyvPmRGXq1lkMIzZemIJqm6o7uqMb57WN87I2Lo+QRtjuea1UHLMr9PnE+UIYjj7xCrenoOQt4yeGewx9nLwzBVzSOzFTF6/j35pvggvCaRMns=,iv:NqrARJU/aZfXUH4Io90zeDtoFBo8FSRmlsjYqxc7MrU=,tag:pJ5c29+4eXp9KzX3Xh8AMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
