#ENC[AES256_GCM,data:GreQ1kHER8J92/MwsWeSs3wvCRMgMl3L2BQzo5hWh8lM523Yh+sR08Oe/SIYLvphUSTAFKOmu8GQ+sZIlZZQcRPzLOdTP0tH0KhEzzlxDPw=,iv:9y0GorEdlkKkkCNam5N0/ywxASnOzOFKDKlX2aFk7Ro=,tag:r2GF3Jp+48YftqfISXlubg==,type:comment]
#ENC[AES256_GCM,data:OC6pdrIDPrfk7jJMN3oiyHKDEhMfWLV2NvT9hYOUsEr9+W+qACQulYtPqdKrFcmRSM8dxNsyxanWoW6P81KTQg8eQnVNWc0TbK33GQ==,iv:1OqJXxlweYxJAuSbyXrpZbGcKiB0EmbC0cGCvyDxJlw=,tag:1OqEpEs2p3+uS4IfoP6aug==,type:comment]
#ENC[AES256_GCM,data:dlx7ZRV3eGcejdjLri17q1HNLOlLNS49J6qwHqpiETCXdWioIp2LBQgrPQ==,iv:me3K7bLJmbUWb4uFqMPIqp+O6ZtVveFLWLs8ldQR0n4=,tag:DlMCFxVl3aFdbSXDdKvOYQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:ppc=,iv:XMx9Qy3Q4d8i7y8I8hHN7hVhtyjBkA0/+U8DAoVm7DU=,tag:6iDBz+RAjUX4yPMjUmCLCg==,type:str]
kind: ENC[AES256_GCM,data:+/HxeZL5,iv:bE1rgsMYVsKgi0LsmOj+n4qkZ5ihs7ph32y9vvJ8/pI=,tag:yTWQZWVyiA/LQ65e2iSM7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1TkWK+3MqWcuiT5ptBKzYuo=,iv:U40rwW6V+8BPw4DgEiiG2M8m+oe3422V/w0sGMsc4q0=,tag:ieiRYFFS5k4PjuptTo5f2w==,type:str]
    namespace: ENC[AES256_GCM,data:S77ekQ==,iv:PSo95AKaSYEiZ54wVwTMUuepcGeuOVXUkAtF/WColek=,tag:TMXv+Ukf5iRNz17TXe0Wig==,type:str]
type: ENC[AES256_GCM,data:hwWmPcISWCaw3ci4yZ5jF7UqRpVsMZy0,iv:JsByVEd3cR5hXWTyVq44keJakeqy6LCSE0wVAWAk8LE=,tag:GXbN4LjHpCPp2COmvb1y+Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:syL3lKDL8A0=,iv:qBE1SwjUw3ywB4Nushep/RY51RMsD5J9oq/wli9yT30=,tag:sX9lkyqfcf5N8/lzwjfZ4w==,type:str]
    password: ENC[AES256_GCM,data:fQLp70D8hnLHmxTx9J6T7T2iCJqbptn/7WLlk3W0btuKgnXP9jmmM5dwpI+cmuT+MMwrpFGOGTDKN0P4BI/mOw==,iv:Khe9jOZSBVBMnwjKN/qUyOwODLfWNN4yQX7T85QOGfY=,tag:W4E1PJypLUnIbpoh+uo8Kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cFFNRkg1YWdINW8zbFM2
            OHRFczZoaWY3a3pZYlpxUE8yNThOeVpXRGlvClAwSmRNamJuL09MMk1zVTVhdWNk
            OXR4QW9JZVJFZ1VYeTkvb0NWQzZ1dDQKLS0tIG1CeUlGZjczQXRlY1FjZ2ZRelRU
            a3owSS9CekF2ZFEvYTVldnp6UVVSdWMKfTqdNyk7kIL85jTDOvyNllftF+ipdiF0
            JRrqX5j6JKYkA6BUb3RKHn495yKJqS56R3jyV9joYnDWTcK7cFu9yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T00:38:50Z"
    mac: ENC[AES256_GCM,data:WPKzHNGy0+35SQVLmv3mGEjVV3GJbFhqusuVzR2k9bbQJtwj+P1diC/T0vfW56Gusd14TMqQ8zgSWFu1u12jKlJ4IH77gPyKEs/LggxeK2BGPARqK4ej3EGuH38zKTcF+XIRI6bHOA/8lIKvvAQxVFNDWDzVeUPSVekhJ61jDRY=,iv:pzl2awXOUBdSUHics+mJ4HkJvnmdLyUkzEBVQGoXXr0=,tag:VDOz0QeNs0l/W01vvcgD8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
