#ENC[AES256_GCM,data:or2nYkEj47lt8VP5SSuNhhth9IgxsxNaYqwiOurR9ae7mQYaWUEL+YNxPO07zCHpBc8iBFs8C+WZIKUwkFCIDehqJWlbzaWYBbQFww==,iv:ntPZuH4aMciEOpsqiJsMMjaInX4bVLWDxMOiwUv0BYw=,tag:44pOFoXlvk5WExK+vdYytg==,type:comment]
#ENC[AES256_GCM,data:bpA6K4RmmQxFdxfWeglZtYZ0vCVmdKPEFU4ceNC7WiB/mYazyFmrtXZIETCOgXuu9rZhUqsFIBOkkSnIUubOI6Oi/nqnzJo=,iv:Mj1zfF7UbKSWzGE1/zf6Fw5cPndewEX/9ChM/q6BP80=,tag:EhrEVHMgXEKb/QSX6YP2lg==,type:comment]
#ENC[AES256_GCM,data:Px8TPQ8N93bILCKtGH3rT0L81FvuhQ+gMCvTNtmUV8pUH59mBDR78c+2CazjHE8iNq01vkLUO6VOjyF59tPc3FjIgQ8hhvX88m2O,iv:e2I6rikYz/RTd3omKUJ2y2A9QxT9vbQZXVwQOO5K8xo=,tag:JxqvbWEiSJSLN1sOjIQx6g==,type:comment]
#ENC[AES256_GCM,data:xyv+W3WZGU3FIgAgp5yriKz9CVEKGT6hAkFgSXm3AbUy8TaaYpdLKt4=,iv:ZcnK4UfUSmC9hVMQj4IelpKUEPKMOILfd+BaZ6pucyI=,tag:IXMgvvApuvsJ2RIHuj144A==,type:comment]
apiVersion: ENC[AES256_GCM,data:+sg=,iv:hdSZLAYJyd+/1OG8jmk5XaS+Q8nkWvlGv7P3JexlTlA=,tag:4371ohby+nwZuv3uelDhNw==,type:str]
kind: ENC[AES256_GCM,data:7KZc0vUq,iv:RMbxa1pJjzPaV4VZm3qtpUxHtz1IpCAYUKc07ySDu14=,tag:XsVyTuZ5kBzmHWsyZzYvtQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oLCivbzh0fXr+KPFoEojNwJDoVXl,iv:1nD/cSJcwUTjjxEkhqHqIZ+4vc8FZLhOtxMFTX8saDU=,tag:KAmDpVSRY/3sCnUH1u51xA==,type:str]
    namespace: ENC[AES256_GCM,data:MtHCwQ==,iv:Jtw1WYdz4EZA0/ZczSsYe5XdFKw187GUIc+ccDkR+FA=,tag:zXwNf7sKHEBT0kFPbnEuIw==,type:str]
type: ENC[AES256_GCM,data:ZhM4S6f2iVZsOWppxJUhGpn71VfsflDi,iv:fsEWLK8RLSKrGh56yim2EbFMxFg9yX8ZXuHaa81Iuu4=,tag:giPvqpHzb2MLIfbbDiazGQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:74si3ASzrs8QsT4G,iv:CI+8xodzUmRS+6lucy3XiOQO0JxDkiuGEFmBwQz5sHE=,tag:NF3HR7GuYXDoT1ggIdIkcA==,type:str]
    password: ENC[AES256_GCM,data:eo6jj+Ehq1hGNDyQfqMmnVSL20/wCYBLoqtkAKM3/3vRIvvszKFbWA==,iv:reykUWQJW+A8nypvTKOmNvtGF9gBQpM8+3VSk9jYeNE=,tag:Y+Ep29F2DxtxWQlkkX9tXA==,type:str]
sops:
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaGZuSVJQRERraStJeXUv
            SW1FTG1EU3pvMUNvUU9FS2R3Y1lzS1hwa3lBCjU3NWRRbW5FT2xObXozUXNSNTN2
            ZmRvUnl5WDlkeWppMXc3N0xrdEh5STgKLS0tIFlmT1hLOGFSalArM1BQWDN6NEVn
            U1c2bDNHYXRKekFLTDdWMnJzWG94ckUK/E9VJ4vFt3DT1+IBeHQur/L/TFD6e7RF
            Ja0KzzLKzUosOhOOGzt2KfAl1zEHIWAprtYI3QhWY/la+yCyOGgrfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T01:42:16Z"
    mac: ENC[AES256_GCM,data:QptaPKddts5GVY/h3i+hf73puhg1DJJL0fNL8+PlVb+BFXjte06RP3EJxKzcefTNGyFvyIlPY2ABH6nmXVAa99QtIXydnnSvvKM98jO0wzTRvdLkknwgUr+ocqgZalmP/f0sGhoeBhTkic365r2/G+JqtFHqk0gp7vTmhWHGW9I=,iv:c9Urj5Prnes18bAIulnaOVHUgW4gC4mTjKdMsLnUAAI=,tag:IR46qB/WEBqcQxd50sSGWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
