#ENC[AES256_GCM,data:B0/Mwvu2blmjtodXJEivzwdRZ5Ed4fHRnR0x8IuWXe0rvcCBzPneJfApO7sDwsMn728xA63qhc+sL5pqq9SlDgYOAAI=,iv:CaTqYNQDCDp5Q64K+iMRlhhMLz2yVDuktNM4P+EflSg=,tag:a4//+Bhv5aN6eCptnRhyDw==,type:comment]
#ENC[AES256_GCM,data:NKdvsn3BAFsoRkjP4FszH7mgMj3UKkcklvnuOCLZjvoz6i8gK7nSqt07gQXGUcF9rxCjoiovp4Isu92SDPKDonJB9UxKlXn7yQ9dLA==,iv:So10J+IQYaCrM3veBdEQHhJiSh9erVAipiBg6b9Vvcs=,tag:AbVeTwUTKR5Y1Tkv/6XICg==,type:comment]
#ENC[AES256_GCM,data:HEnGeHKqQLqbhV2oyiH1/Lqn8D7oSxp8E3rhl621KUEs1fJ5Pw2jJgM7/m3sHiOepY8x7F/HlkqzFXvsOuMml+I=,iv:UJ3vMEVhFwi4oquUxlU92rU7qDoPtWkdCZVY5F4LzMA=,tag:+tjZj84ChriLfO5HH0tEHA==,type:comment]
apiVersion: ENC[AES256_GCM,data:D10=,iv:/Cdx3rknttITxdQ0MrUxK/D8ugq6KycyrqqS57m19/I=,tag:De9l2mWvEtaDCZtamN+T8g==,type:str]
kind: ENC[AES256_GCM,data:BJ4sLhkM,iv:ZpoR5W1E1YLbstd+5kv1d/5ydprSY5vamMpcbWo1jLo=,tag:Bcrt4vJftnNrIjcAnByg0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EgTP4zBvQARf4Htzzer4bA==,iv:meEp106KCuI+V8+o/ie2rcwUs0ZdpSqAkYCuFWVZVmU=,tag:6DHTvg1PDLXJeFu7hxvEOQ==,type:str]
    namespace: ENC[AES256_GCM,data:ZDwmZA==,iv:Nx9bZ0r9fFDLhe78uybFS9HzFnLRY9+1BChuX32Y6Vs=,tag:hgBgIy+POP7s0JkkMXPyDQ==,type:str]
type: ENC[AES256_GCM,data:7Eo3cJSCDjtFGqo3op4fCbZSDR/KXU4O,iv:d6i/49LmkfNJGut29sAS5Fdy9he+fW44hwYAta0ONPo=,tag:DT6T8ofHhuzC3cXCD/kerQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:7XNjc8tL6w==,iv:6U3zgZZ3Y/7QGjW9Qgm8igfiK/rHFJ2tqAucSsHoeDI=,tag:LqGdCxe+Z1UFIusEmyXq3Q==,type:str]
    password: ENC[AES256_GCM,data:Gp6TzB5Go2l6Mq+xh12LGA5Xf4RfQNGlGEZ2YSjrtA==,iv:K6R3TipwqEpSmsA9xBktVSJfRczRB45JDOp1xljQgco=,tag:0opkd6GWrm4E7aVz/5SMpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16mxws3n4s0my6k5jzy225shmpa36ag35v975xg4j6u7k3rjqn5dqvxw27c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvajUyTlZ4bVd1Q2FpWkNN
            bWJwTCsrTmJLSjNET1c4ekZIaklPSzhRWm1JCmxIcWtleXZjNlZKYnBXMzNzMS94
            Rno3WlpVbS9uVEtUWGJIMlNqalNOTXcKLS0tIEk0RFpFWnpVUW5ISjdBUXNXNVdC
            YjBRSkloSjhrRUhjT3A4ekQ0NmN5MWsK+Ifg3ZByLJR0IfuB2tE62o6Au/oe49va
            0hGQw+9TgXjWDwmO2Q20FLOCV2B9MKUsw83DBP+TgheAzNWgBplbPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T19:40:10Z"
    mac: ENC[AES256_GCM,data:C4WWIM7JRbIAn425hK8ZEkn6RubfU+Q6J3saebw9xxI9rMzPRcg65K+v4v4tvrLWmRFsb7XeWjEhZm0bcd3Z5hxTeV3QO+PzujAHV8E4hqHaH7VCGAtAHuFQH8Md/q3wEZhXYzM2MsLS2+9EJCwKaAXvp73bDQB4FqfC/7ISux4=,iv:EGi0YysNIEH2Mgeo1o6gHPXn/tCHEekW2LmqHhMMN4M=,tag:55dH12r8LpfAcbkqZbUWNw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
